export const segmentation = {
  state: [
    '-',
    'A Coruña',
    'Álava',
    'Albacete',
    'Alicante',
    'Almería',
    'Asturias',
    'Ávila',
    'Badajoz',
    'Baleares',
    'Barcelona',
    'Burgos',
    'Cáceres',
    'Cádiz',
    'Cantabria',
    'Castellón',
    'Ceuta',
    'Ciudad Real',
    'Córdoba',
    'Cuenca',
    'Gipuzkoa',
    'Girona',
    'Granada',
    'Guadalajara',
    'Huelva',
    'Huesca',
    'Jaén',
    'La Rioja',
    'Las Palmas',
    'León',
    'LLeida',
    'Lugo',
    'Madrid',
    'Málaga',
    'Melilla ',
    'Murcia',
    'Navarra',
    'Ourense',
    'Palencia',
    'Pontevedra',
    'Salamanca',
    'Santa Cruz de Tenerife',
    'Segovia',
    'Sevilla',
    'Soria',
    'Tarragona',
    'Teruel',
    'Toledo',
    'Valencia',
    'Valladolid',
    'Vizcaya',
    'Zamora',
    'Zaragoza '
  ],
  education: [
    '-',
    'Sin estudios',
    'Enseñanza obligatoria',
    'Enseñanza Secundaria',
    'Formación universitaria',
    'Formación profesional',
    'Postgrado',
    'Doctorado'
  ],
  sector: [
    '-',
    'Administración y asesoría',
    'Agricultura, ganadería',
    'Arte y Cultura',
    'Ciencia y tecnología',
    'Comercio',
    'Construcción',
    'Deporte y ocio',
    'Educación formal e informal',
    'Exportación/importación',
    'Finanzas, seguros y bienes inmuebles',
    'Fuerzas de seguridad, bomberos, justicia',
    'Industria pesada y ligera',
    'Logística y transporte',
    'ONGs, activismo y voluntariado',
    'Otros',
    'Periodismo y opinión',
    'Publicidad y marketing',
    'salud y bienestar',
    'Servicio público',
    'Tecnología y telecomunicaciones',
    'trabajo doméstico, cuidados',
    'Turismo y hostelería'
  ],
  sex: [
    '-',
    'Otro',
    'Mujer',
    'Hombre'
  ],
  civilState: [
    '-',
    'Soltero',
    'Casado',
    'Divorciado',
    'Viudo',
    'otro'
  ]
}
